### ISSUE TITLE
Demo the milestone 2 reqs

### ISSUE THREAD

**Issue by 2byrds** [roots-id/DoulaID#15]
- [ ] Show the team
- [ ] Adjust based on feedback
- [ ] Create a highlight video and post to the repo
- [ ] Close this issue.
